### ISSUE TITLE
add firewalld support

### ISSUE THREAD

**Issue by puneetse** [clearlinux/tallow#11]
A feature request to add firewalld as an option for the `ipt_tool` and use it to configure ipsets when it is in use.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-setting_and_controlling_ip_sets_using_firewalld

https://firewalld.org/documentation/man-pages/firewalld.ipset.html

**Comment by ahkok** [comment]
if I google for `ipt_tool` it shows me 1 result: **this issue**. Oops?

**Comment by ahkok** [comment]
I don't see how I can insert values using `firewalld` with a `timeout` value, which would be the main requirement (or, a default timeout value for entries in the `ipset`).

We also have the problem of ordering. We can certainly `After=firewalld.service` in `tallow.service` to make the dependency optional but force ordering.

Then there's the "detection" problem. Ideally this is transparent without requiring more libraries to be linked - something where `tallow` sees firewalld is present and operational or not.

I don't have any ideas yet on any of these :)

**Comment by puneetse** [comment]
> I don't see how I can insert values using `firewalld` with a `timeout` value, which would be the main requirement (or, a default timeout value for entries in the `ipset`).

It looks like this is possible by specifying an "option" when adding the firealld.ipset entry.
https://firewalld.org/documentation/man-pages/firewalld.ipset.html

and:
> There is one limitation with ipset usage in firewalld though:
>
>If the timeout option is used for an ipset, then it will not be possible to list the entries of the ipset with firewalld as the timeout is directly done in kernel space and adding additional timers for each entry could result in a high load of firewalld.

https://firewalld.org/2015/12/ipset-support

**Comment by ahkok** [comment]
Not being able to list the ipset with firewalld seems OK. We may want to document it. That explains maybe why you couldn't see it in the first place?

**Comment by ahkok** [comment]
`v17`
