### ISSUE TITLE
v17 doesn't block anything (sans `firewalld`)

### ISSUE THREAD

**Issue by ahkok** [clearlinux/tallow#14]
Confirmed on one system - loads of login failures:

- `v17` no blocks
- `v16` blocks right away almost

**Comment by ahkok** [comment]
@puneetse Looks like something went wrong in the logic there?

**Comment by puneetse** [comment]
fixed by https://github.com/clearlinux/tallow/commit/348fd7d744e9eafe67bab7e173e04ffce007508b
