### ISSUE TITLE
Block occurs after apparent journal rotation

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/tallow#7]
In course of debugging an issue with the clr_debug_daemon today, tallow suddenly blocked my IP address.  From the evidence in the journal, I see these two log messages (IP address and hostname masked):

```
May 25 20:20:05 HOSTNAME tallow[8811]: Journal was rotated, resetting
May 25 20:20:05 HOSTNAME tallow[8811]: Blocked xx.xx.xx.xx
```

The previous ~50 journal log messages were all from clr_debug_daemon, and all have the same timestamp as above (May 25 20:20:05).

I was locked out of my ssh session a couple of days ago as well, and from the evidence in the journal, I suspect a similar sequence of events: clr_debug_daemon was spamming the journal, and then tallow blocked my IP. Except there were two "journal rotated" log messages that time...

```
May 23 22:42:11 HOSTNAME tallow[302]: Journal was rotated, resetting
May 23 22:42:11 HOSTNAME tallow[302]: Blocked xx.xx.xx.xx
May 23 22:42:11 HOSTNAME tallow[302]: Journal was rotated, resetting
```

**Comment by ahkok** [comment]
the way that tallow looks at the journal explicitly filters out non-sshd messages, so the clr-debug-daemon stuff is never seen by tallow.

**Comment by ahkok** [comment]
The fact that we're reparsing already seen messages is clearly a bug. I don't know yet whether that's due to the systemd-journald API implementation or its use, this needs work. This part of the code is very fragile and I'm not happy with it as is.

**Comment by ahkok** [comment]
looks like e4b39777048b1ccfc815189fdb51019c5e8de903 properly fixes this issue.
