### ISSUE TITLE
Block happened on my local home network 192.168...

### ISSUE THREAD

**Issue by seanvk** [clearlinux/tallow#9]
Just feedback:

Butter fingered the password a few times on ssh to my Clear laptop from another machine at home and was surprised to find tallow was running after a fresh install and it blocked my other machine.

I didn't realize Clear Linux enables this by default
I didn't realize it operates on my local network

Sean

**Comment by bswinnerton** [comment]
I too was surprised that Clear Linux enables this by default. Is there a way to opt out of tallow?

**Comment by ahkok** [comment]
`v13` will have this. Pushing to clear.
